spring.application.name=catalog-service

server.port=${SERVER_PORT:8081}
server.servlet.context-path=/api/v1

app.cors.allowed-origins=${CORS_ALLOWED_ORIGINS:http://localhost:3000,http://localhost:5173}

# ----------------------------------------
# KONFIGURASI DATABASE (POSTGRESQL / NEON DB)
# ----------------------------------------
spring.datasource.url=${DB_URL:jdbc:postgresql://localhost:5432/liveeuy-catalog-db}
spring.datasource.username=${DB_USERNAME:postgres}
spring.datasource.password=${DB_PASSWORD:postgrespassword}
spring.datasource.driver-class-name=org.postgresql.Driver

# ----------------------------------------
# JPA & HIBERNATE
# ----------------------------------------
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=false
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.datasource.hikari.connection-timeout=30000
spring.datasource.hikari.maximum-pool-size=5

# ----------------------------------------
# KEAMANAN & OAUTH2 RESOURCE SERVER (JWT ASIMETRIS / JWKS)
# ----------------------------------------
spring.security.oauth2.resourceserver.jwt.jwk-set-uri=${JWK_SET_URI:http://localhost:8080/.well-known/jwks.json}
spring.security.oauth2.resourceserver.jwt.issuer-uri=${JWT_ISSUER:liveeuy-auth-service}
app.jwt.issuer=${JWT_ISSUER:liveeuy-auth-service}
