spring.application.name=catalog-service

server.port=8081
server.servlet.context-path=/api/v1

app.cors.allowed-origins=http://localhost:3000,http://localhost:5173

# ----------------------------------------
# KONFIGURASI NEON DB
# ----------------------------------------
spring.datasource.url=${DB_URL}
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}
spring.datasource.driver-class-name=org.postgresql.Driver

# ----------------------------------------
# JPA & HIBERNATE
# ----------------------------------------
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=false
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.datasource.hikari.connection-timeout=30000
spring.datasource.hikari.maximum-pool-size=5